### ISSUE TITLE
rewire-test-helper can cause crashes for large test suites

### ISSUE THREAD

**Issue by lukastaegert** [rincedd/rewire-test-helper#2]
Hi,

for some time we had issues with our test suite crashing in various browsers after a certain amount of tests. By examining the work of our mocha test runner, most notably logging the value of `i` in the break condition of

`Runner.prototype.hook() > next(i)`

I discovered that even though we placed all calls to `rewire()` inside describe blocks, apparently global `afterEach`s are created by each call to rewire. This resulted in >2000(!) afterEach calls before our tests crashed, which is not surprising as those afterEach hooks are handled in a synchronous recursive loop, i.e. there is probably a call stack limit problem behind this.

For now we solved the problem  by not using the auto-restore functionality but instead restoring manually. I am not sure how it might be possible to solve this problem, maybe creating one global afterEach and using a global array of rewired values could work.

On the other hand, the latest version of babel-plugin-rewire now features a global `__rewire_reset_all__` function which might make a lot of this logic obsolete.

**Comment by rincedd** [comment]
It seems like you found a major issue here. I'd suggest deprecating `rewire-test-helper` altogether in favor of the Babel plugin's `__rewire_reset_all__` function.

**Comment by rincedd** [comment]
I added a deprecation warning and marked the package as deprecated on NPM in favor of the new functionality of `babel-plugin-rewire` (see speedskater/babel-plugin-rewire/issues/114). Closing.
